"""empty message

Revision ID: 6413d3154341
Revises: 513bc8f9c3e6
Create Date: 2020-02-15 18:27:37.819128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6413d3154341'
down_revision = '513bc8f9c3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))

    op.batch_alter_table()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###
